### PR TITLE
prettify code

### PR DESCRIPTION
**Pull request by marechal-p**
Cette PR setup `prettier` pour automatiquement formatter le code source avant de build.

### CODE REVIEW

**Review by RubenLaden — APPROVED** [review]
That's much prettier indeed. I ran the tests locally and the results have the same inconsistencies as the "unprettyfied" version, so it doesn't seem to break anything.

**Comment by yvanross** [comment]
Will not add it because team's already try to use it and ask for removal because it mess up code.

**Comment by marechal-p** [comment]
@yvanross Since the point of Prettier is to fix source code styling, I am a bit surprised to hear this. I can rewrite the PR to not add prettier into the repo, but still use it to reformat the current code. What do you think?

**Comment by yvanross** [comment]
You can use it locally on your project but lots of team complaint about it so I prefer to not add it to the template project.  Thanks.

**Comment by RubenLaden** [comment]
I use Prettier in my fork and it runs flawlessly. If the code mess up mentionned is the `TS2304: Cannot find name 'PathLike'` error, it doesn't come from Prettier. This commit 5144ebc4f0d624856252b3d786988933553dfef6 fixed it. What about merging prettified changes but disabling the auto-formatting ?

**Comment by yvanross** [comment]
It is not related to pathlike problem.  But I am ok to integrate it disabled by default. You must update the README.md file to explain how to enable it. Thanks.

**Pull request closed without merging**
